# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='gallery.Category'),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Location'),
        ),
        migrations.AddField(
            model_name='image',
            name='picha',
            field=models.ImageField(null=True, upload_to='articles/'),
        ),
    ]
