# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190301_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='picha',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='picha_name',
            new_name='image_name',
        ),
    ]
