# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190305_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='location',
            new_name='picha_location',
        ),
    ]
