# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190303_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
